version: '3'
services:
  database:
    image: postgres:9.6.1
    env_file:
      - .postgres.env
    ports:
      - "5432:5432"
    depends_on:
      - db_data
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - onms
    deploy:
      mode: replicated
      replicas: 1
  opennms:
    image: opennms/horizon-core-web:latest
    env_file:
      - .opennms.env
      - .postgres.env
    depends_on:
      - database
    volumes:
      - opennms_data:/opennms-data
    volumes:
      - opennms_etc:/opt/opennms/etc
    networks:
      - onms
    command: ["-s"]
    ports:
      - "8980:8980"
      - "18980:18980"
      - "1099:1099"
      - "8101:8101"
      - "61616:61616"
      - "5817:5817"
      - "162:162/udp"
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: ["CMD", "ping", "localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
volumes:
  database_data:
    driver: local-persist
    driver_opts:
      mountpoint: "/swarm/volumes/database_1/data"
      name: "database_data"   
  opennms_data:
    driver: local-persist
    driver_opts:
      mountpoint: "/swarm/volumes/onms_1/data"
      name: "opennms_data"
  opennms_etc:
    driver: local-persist
    driver_opts:
      mountpoint: "/swarm/volumes/onms_1/etc"
      name: "opennms_etc"
networks:
  onms:
